version: 2
jobs:
   test:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: yarn install
       - run: CI=true yarn test
   deploy:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: ./deploy-scripts/build-upload.sh
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

