version: 2
jobs:
   test:
     docker:
       - image: circleci/node:10.13
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm test
   deploy:
     docker:
       - image: circleci/node:10.13
     steps:
       - checkout
       - run: sudo apt-get update && sudo apt-get install -y awscli
       - run: ./deploy-scripts/build-upload.sh
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

